# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "attr_encodable"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Flip Sasser"]
  s.date = "2012-10-16"
  s.description = "\n    attr_encodable enables you to set up defaults for what is included or excluded when you serialize an ActiveRecord object. This is especially useful\n    for protecting private attributes when building a public API.\n  "
  s.email = "flip@x451.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "lib/attr_encodable.rb",
    "lib/encodable.rb",
    "lib/encodable/active_record.rb",
    "lib/encodable/active_record/class_methods.rb",
    "lib/encodable/active_record/instance_methods.rb",
    "lib/encodable/array.rb"
  ]
  s.homepage = "http://github.com/Plinq/attr_encodable"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "An attribute black- or white-list for ActiveRecord serialization"
  s.test_files = ["spec/attr_encodable_spec.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0"])
  end
end

